---
- name: checking for agent install
  stat:
    path: '{{ redhat_cylance_agent_path }}/desktop/cylance'
  register: agent

- debug:
    msg: "cylance agent not found (installing)"
  when: not agent.stat.exists

- debug:
    msg: "cylance agent found (skipping install)"
  when: agent.stat.exists

- name: create {{ redhat_cylance_agent_path }} directory
  file:
    path: '{{ redhat_cylance_agent_path }}'
    state: directory
    mode: 0500
  when: not agent.stat.exists

- name: move config_defaults.j2 to {{ redhat_cylance_agent_path }}/config_defaults.txt directory
  template:
    src: config_defaults.j2
    dest: '{{ redhat_cylance_agent_path }}/config_defaults.txt'
    mode: 0400
  when: not agent.stat.exists

- name: install cylance agent (redhat)
  yum:
    name: '{{ redhat_cylance_agent_url }}'
    state: present
    validate_certs: no
    disable_plugin: "yum-rhn-plugin"
    disablerepo: "*"
    download_dir: '{{ redhat_cylance_agent_path }}'
  when: not agent.stat.exists

- name: check agent link status
  command: '{{ redhat_cylance_agent_path }}/desktop/cylance -s'
  become: yes
  register: cylance_link
  when: not agent.stat.exists
  ignore_errors: yes # adding ignore_errors since this will fail until you have an environment with connectivity to a cylance master host

- name: register cylance agent (redhat)
  command: '{{ redhat_cylance_agent_path }}/desktop/cylance -r {{ agent_secrets.cylance_pid_id }}'
  become: yes
  when: not agent.stat.exists
  ignore_errors: yes # adding ignore_errors since this will fail until you have an environment with connectivity to a cylance master host

- name: verify cylance started
  service:
    name: cylancesvc
    state: started
  ignore_errors: yes # adding ignore_errors since this will fail until you have an environment with connectivity to a nessus master host
