---
- name: create {{ redhat_agent_path }} directory
  file:
    path: '{{ redhat_agent_path }}'
    recurse: yes
    state: directory
    mode: '0755'

- name: install cylance agent (redhat)
  yum:
    name: '{{ redhat_cylance_agent_url }}'
    state: present
