---
- name: checking for agent install
  win_service:
    name: cylancesvc
  register: agent

- debug:
    msg: "cylance agent not found (installing)"
  when: not agent.exists

- debug:
    msg: "cylance agent found (skipping install)"
  when: agent.exists

- name: create {{ windows_agent_log }} directory
  win_file:
    path: '{{ win_agent_path }}'
    state: directory
  when: not agent.exists

- name: create {{ win_agent_logs }} directory
  win_file:
    path: '{{ win_agent_logs }}'
    state: directory
  when: not agent.exists

- name: install cylance agent (windows)
  win_package:
    path: '{{ windows_cylance_agent_url }}'
    state: present
    log_path: '{{ windows_agent_log }}\cylance_log.txt'
    product_id: '{{ windows_cylance_product_id }}'
    arguments:
      - PIDKEY={{ cylance_pid_id }}
      - LAUNCHAPP=0
      - VENUEZONE={{ cylance_venue_id }}
  when: not agent.exists

- name: register cylance agent (windows)
  command: '{{ windows_cylance_agent_path }}\cylancesvc.exe -r {{cylance_pid_id}}'
  when: not agent.exists
  ignore_errors: yes # adding ignore_errors since this will fail until you have an environment with connectivity to a cylance master host

- name: verify cylance started
  win_service:
    name: cylancesvc
    state: started
    start_mode: auto
