---
- name: create {{ windows_agent_log }} directory
  win_file:
    path: '{{ windows_agent_log }}'
    recurse: yes
    state: directory

- name: create {{ windows_agent_path }} directory
  win_file:
    path: '{{ windows_agent_path }}'
    recurse: yes
    state: directory

- name: install cylance agent (windows)
  win_package:
    path: '{{ windows_cylance_agent_url }}'
    state: present
    log_path: '{{ windows_agent_log }}\\cylance_log.txt'
    product_id: '{{ windows_cylance_product_id }}'
    validate_certs: no
    arguments:
      - /PIDKEY={{ cylance_pid_id }}
      - /LAUNCHAPP=0
      - /VENUEZONE={{ cylance_venue_id }}
